### ISSUE TITLE
indent for android

### ISSUE THREAD

**Issue by hius74** [mangstadt/vinnie#1]
Current realization FoldedLineWriter indent always one char. The result output is
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:10 =D0=AD=D1=82=D0=B0=D0=B6 =D0=
 =A1=D0=B5=D1=80=D0=B3=D0=B5=D0=B9

Second line (continue from FN) has first chards ' ' (space) as default indent.

when import vcard file on android phone I has error. Android not support space in as first characters.

Please, allow in file com.github.mangstadt.vinnie.io.FoldedLineWriter set empty indent.
public void setIndent(String indent) { 
if (indent.length() == 0) {
			throw new IllegalArgumentException("Indent string cannot be empty.");
} 
replace 
if (indent == null || indent.length() == 0)  {
this.indent = "";
}

As a result: - no space on second line and vCard correct import on Android phone,
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:10 =D0=AD=D1=82=D0=B0=D0=B6 =D0= =A1=D0=B5=D1=80=D0=B3=D0=B5=D0=B9

Thanks.

**Comment by mangstadt** [comment]
Thanks for the report.  Fixed in 9235609703ae7cb59c356dbb18da1d642bfd4bbb.

Workaround: Disable line folding altogether.

```java
VObjectWriter writer = ...
writer.getFoldedLineWriter().setLineLength(null);
```
