### ISSUE TITLE
Not deployable as OSGI bundle

### ISSUE THREAD

**Issue by stoerr** [mangstadt/vinnie#2]
biweekly is in itself nicely deployable as an OSGI bundle. But starting from 0.6.0 it uses vinnie, and if I try to deploy vinnie as a bundle I get "Bundle-SymbolicName header missing, cannot install bundle" from Felix. It would be nice if vinnie was deployable, too - otherwise we are stuck with biweekly 0.5.0. Thank you so much!

**Comment by mangstadt** [comment]
Ok, I updated vinnie to use OSGi and published a new version Maven Central (2.0.2).  I also published a new biweekly build to Maven Central (0.6.2) which uses the new vinnie build.  Let me know how it works out.
